### ISSUE TITLE
Error while running 

### ISSUE THREAD

**Issue by TwistedVision518** [servetgulnaroglu/cube.c#3]
Error is

 *  Executing task: C/C++: gcc-9 build active file 

Starting build...
/usr/bin/gcc-9 -fdiagnostics-color=always -g /home/pranav/spinningcube.c -o /home//spinningcube
/usr/bin/ld: /tmp/ccaqCFiq.o: in function `calculateX':
/home//spinningcube.c:25: undefined reference to `sin'
/usr/bin/ld: /home//spinningcube.c:25: undefined reference to `sin'
/usr/bin/ld: /home//spinningcube.c:25: undefined reference to `cos'
/usr/bin/ld: /home//spinningcube.c:25: undefined reference to `cos'
/usr/bin/ld: /home//spinningcube.c:25: undefined reference to `sin'
/usr/bin/ld: /home//spinningcube.c:25: undefined reference to `cos'
/usr/bin/ld: /home//spinningcube.c:26: undefined reference to `cos'
/usr/bin/ld: /home//spinningcube.c:26: undefined reference to `sin'
/usr/bin/ld: /home//spinningcube.c:26: undefined reference to `sin'
/usr/bin/ld: /home//spinningcube.c:26: undefined reference to `sin'
/usr/bin/ld: /home//spinningcube.c:26: undefined reference to `cos'
/usr/bin/ld: /home//spinningcube.c:26: undefined reference to `cos'
/usr/bin/ld: /tmp/ccaqCFiq.o: in function `calculateY':
/home//spinningcube.c:30: undefined reference to `cos'
/usr/bin/ld: /home//spinningcube.c:30: undefined reference to `cos'
/usr/bin/ld: /home//spinningcube.c:30: undefined reference to `sin'
/usr/bin/ld: /home//spinningcube.c:30: undefined reference to `cos'
/usr/bin/ld: /home//spinningcube.c:31: undefined reference to `sin'
/usr/bin/ld: /home//spinningcube.c:31: undefined reference to `sin'
/usr/bin/ld: /home//spinningcube.c:31: undefined reference to `sin'
/usr/bin/ld: /home//spinningcube.c:31: undefined reference to `cos'
/usr/bin/ld: /home//spinningcube.c:31: undefined reference to `sin'
/usr/bin/ld: /home//spinningcube.c:31: undefined reference to `sin'
/usr/bin/ld: /home//spinningcube.c:32: undefined reference to `cos'
/usr/bin/ld: /home//spinningcube.c:32: undefined reference to `sin'
/usr/bin/ld: /tmp/ccaqCFiq.o: in function `calculateZ':
/home//spinningcube.c:36: undefined reference to `cos'
/usr/bin/ld: /home//spinningcube.c:36: undefined reference to `cos'
/usr/bin/ld: /home//spinningcube.c:36: undefined reference to `sin'
/usr/bin/ld: /home//spinningcube.c:36: undefined reference to `cos'
/usr/bin/ld: /home//spinningcube.c:36: undefined reference to `sin'
collect2: error: ld returned 1 exit status

Build finished with error(s).

 *  The terminal process terminated with exit code: -1. 
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by scorpius2k1** [comment]
On some systems, the math functions are in a separate library, which needs to be linked explicitly. Simply pass the option -lm when compiling (linking) your program, and everything should work.

Try (may need to replace gcc with your specific gcc-9):
`gcc -lm spinningcube.c`

Hope this helps!

**Comment by TwistedVision518** [comment]
thanks it does
