### ISSUE TITLE
how run this cube in windows os?

### ISSUE THREAD

**Issue by scrashqst** [servetgulnaroglu/cube.c#4]
how run this code in windows?

**Comment by CesarxArteaga** [comment]
use cygwin and make sure install gcc packages

**Comment by Daniate** [comment]
I created a pull request to support it: [https://github.com/servetgulnaroglu/cube.c/pull/8](https://github.com/servetgulnaroglu/cube.c/pull/8)

**Comment by servetgulnaroglu** [comment]
Thank you @Daniate, i've merged it
