### ISSUE TITLE
Font used in youtube video? 

### ISSUE THREAD

**Issue by supercomputer1** [servetgulnaroglu/cube.c#5]
I'm sorry for asking a question this way, but there was no information either on your youtube page or in your repositories regarding what font you are using in the youtube video coding this project. Do you have the time to provide it? Many thanks!

**Comment by sajjad-salam** [comment]
its Magistral font
this is download url 
https://dafontnew.com/magistral-font-free-download/#google_vignette

**Comment by servetgulnaroglu** [comment]
DejavuSans
